### ISSUE TITLE
On my fork, with your new background, after typing a lot, it's still not lined up. 

### ISSUE THREAD

**Issue by josheewa** [Legend-of-iPhoenix/editor#10]
Any more ideas?
@Legend-of-iPhoenix @LAX18

**Comment by josheewa** [comment]
And, the first line at the top is really kinda annoying. How about a ton of placeholder spaces that get replaced, and those spaces are underlines red?

**Comment by Legend-of-iPhoenix** [comment]
No, that's a terrible idea because accessibility and just eww.

My thing works. I don't know what you changed, because it worked 100% on all devices I own.

**Comment by josheewa** [comment]
I KNOW. 
If you type to much on computer, it gets out of line. okay?
