### ISSUE TITLE
Should we fork?

### ISSUE THREAD

**Issue by npease18** [Legend-of-iPhoenix/editor#2]
Should we fork? Would it make the project more public?

**Comment by josheewa** [comment]
I forked, but Idk. We can delete it if necessary. Or rename it.

**Comment by npease18** [comment]
Okay thanks

**Comment by Legend-of-iPhoenix** [comment]
You can just create a new branch if you want @jcgter777 and @LAX18 

It might be easier to collaborate that way. I've put restrictions on master so that we can't push commits to it without at least one other person approving it (I am included in this).

**Comment by josheewa** [comment]
Oh okay. I forked so I can do mine, then upload at once to reduce commit #s. @Legend-of-iPhoenix is that a good idea? 

EDIT: I'll still make my own branch, then just upload to that. Good?

**Comment by Legend-of-iPhoenix** [comment]
@jcgter777, we can squash and merge :) 

It crunches it down into one commit :)

**Comment by Legend-of-iPhoenix** [comment]
I think the discussion in here is completed, closing issue (reopen it if needed)

**Comment by josheewa** [comment]
Okey
