### ISSUE TITLE
Lines don't line up.

### ISSUE THREAD

**Issue by Legend-of-iPhoenix** [Legend-of-iPhoenix/editor#8]
**Describe the bug**
Text doesn't line up with lines.
**Expected behavior**
Text lining up with lines

**Screenshots**
![f323bb14-0a6d-42e4-8c79-f7c9450a7add](https://user-images.githubusercontent.com/32944537/41206003-5316faf6-6ccb-11e8-8040-7e8ed6a57f4b.jpeg)

**Desktop (please complete the following information):**
 - OS: iOS, maybe desktop
 - Browser: safari, maybe others 
 - Version n/a

(If you need help, I might be able to help)

**Comment by josheewa** [comment]
I DON'T KNOW HOW!

yes I need help

**Comment by Legend-of-iPhoenix** [comment]
I think you can fix it by explicitly setting the text size to be the distance between the lines. I'm not entirely sure, I have to do some research.

@jcgter777

**Comment by Legend-of-iPhoenix** [comment]
check https://github.com/jcgter777/TextEditOnline/pull/1

**Comment by josheewa** [comment]
hmmm?
